export interface Question {
    id: number;
    text: string;
    image?: string;
    options: { id: string; text: string }[]
    correctOption: string;
}

export const questions: Question[] = [
    {
        id: 1,
        text: 'Какое количество пересечений проезжих частей на этом перекрестке?',
        image: 'https://kulager-auto.kz/storage/questions/video/rnA0sRbpS1KngUPQWF347iJvoYXtKEXYPrzM2fzy.mp4',
        options: [
            { id: 'A', text: 'Одно' },
            { id: 'B', text: 'Два' },
            { id: 'C', text: 'Три' },
            { id: 'D', text: 'Четыре' },
        ],
        correctOption: 'B',
    },
    {
        id: 2,
        text: 'Уступите ли Вы дорогу автобусу при повороте налево на перекрестке?',
        image: 'https://kulager-auto.kz/storage/questions/video/cwQTQ4P9fuQZdwWr6aVddiF2RLkxwjazw05QSIHw.mp4',
        options: [
            { id: 'A', text: 'Да' },
            { id: 'B', text: 'Нет' },
        ],
        correctOption: 'A',
    },
    {
        id: 3,
        text: 'Разрешается ли Вам стоянка после проезда данных дорожных знаков?',
        image: 'https://kulager-auto.kz/storage/questions/video/eGzrlsZAkdbXhvngNMnDy4XFMyxDKMcU4D6JChBQ.mp4',
        options: [
            { id: 'A', text: 'Разрешается' },
            { id: 'B', text: 'Разрешена, если вы обслуживаете предприятия в зоне действия данных знаков' },
            { id: 'С', text: 'Запрещается' },
        ],
        correctOption: 'A',
    },
    {
        id: 4,
        text: 'Как следует поступить, если у Вашего автомобиля во время движения произошел прокол шины колеса?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Резко повернуть рулевое колесо направо и нажать на педаль тормоза' },
            { id: 'B', text: 'Крепко держать рулевое колесо и плавно остановиться' },
            { id: 'C', text: 'Выключить двигатель и включить стояночный тормоз' },
        ],
        correctOption: 'B',
    },
    {
        id: 5,
        text: 'Если Вы движетесь со скоростью менее 40 км/ч, по какой из полос Вам разрешается продолжить движение?',
        image: 'https://kulager-auto.kz/storage/questions/video/0EL4bzd7wxNwkphTcDxOxCfHXztohPZo4BgcKbek.mp4',
        options: [
            { id: 'A', text: 'По средней полосе' },
            { id: 'B', text: 'По крайней левой полосе' },
            { id: 'C', text: 'По крайней правой полосе' },
            { id: 'D', text: 'По любой из полос движения' },
        ],
        correctOption: 'C',
    },
    {
        id: 6,
        text: 'В каких случаях разрешена установка фары-прожектора и фары-искателя на транспортном средстве?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'В случаях, если это предусматривается заводской комплектацией транспортного средства' },
            { id: 'B', text: 'В случаях получения разрешения КАП' },
            { id: 'C', text: 'В любых случаях по желанию водителя' },
        ],
        correctOption: 'B',
    },
    {
        id: 7,
        text: 'Разрешен ли Вам обгон мотоцикла на пешеходном переходе в данной ситуации?',
        image: 'https://kulager-auto.kz/storage/questions/video/WLN9SaFUlblETbDHeFGf1vFERFMq1ULDLbfJcWOt.mp4',
        options: [
            { id: 'A', text: 'Разрешен' },
            { id: 'B', text: 'Запрещен' },
        ],
        correctOption: 'A',
    },
    {
        id: 8,
        text: 'При торможении автомобиля Вам рекомендуется:',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Обратить внимание на исправность ремня безопасности' },
            { id: 'B', text: 'Обратить внимание на обстановку сзади, через зеркало заднего вида' },
            { id: 'C', text: 'Обратить внимание на показания спидометра' },
        ],
        correctOption: 'B',
    },
    {
        id: 9,
        text: 'Горизонтальная разметка в виде треугольника на полосе движения информирует водителя:',
        image: 'https://kulager-auto.kz/storage/questions/video/GA6geqICzT0xZSRFJj88V0QhstTOEfKFQMSgXjHv.mp4',
        options: [
            { id: 'A', text: 'О приближении к опасному участку дороги' },
            { id: 'B', text: 'О необходимости остановиться перед ней' },
            { id: 'C', text: 'О приближении к другой разметке, которая указывает место, где необходимо уступить дорогу' },
        ],
        correctOption: 'C',
    },
    {
        id: 10,
        text: 'Путь, пройденный автомобилем с момента обнаружения Вами опасности и до полной остановки, называется:',
        image: 'https://kulager-auto.kz/storage/questions/video/0tP8NKd9oqcR9pqEh5b1Q4tSBJeNC6COxoKgtQuu.mp4',
        options: [
            { id: 'A', text: 'Тормозной путь' },
            { id: 'B', text: 'Остановочный путь' },
            { id: 'C', text: 'Путь, пройденный за время Вашей реакции' },
            { id: 'D', text: 'Путь, пройденный за время срабатывания тормозного привода' },
        ],
        correctOption: 'B',
    },
    {
        id: 11,
        text: 'С какой максимальной скоростью Вам разрешается движение по примыкающей слева дороге?',
        image: 'https://kulager-auto.kz/storage/questions/video/Aa1tZ78gFTUn4zwN3zUJfIkuBAxv2NHkw1bUP17n.mp4',
        options: [
            { id: 'A', text: '60 км/ч' },
            { id: 'B', text: '70 км/ч' },
            { id: 'C', text: '90 км/ч' },
            { id: 'D', text: '100 км/ч' },
            { id: 'E', text: '110 км/ч' },
        ],
        correctOption: 'A',
    },
    {
        id: 12,
        text: 'Если водитель обгоняющего Вас автомобиля испытывает затруднения при завершении обгона из-за малой дистанции между Вашим и движущимся впереди автомобилем, Вам рекомендуется:',
        image: 'https://kulager-auto.kz/storage/questions/video/vaNSqvDklgLcpbWzEmJlRQpdRWcCPRHbYzJstghO.mp4',
        options: [
            { id: 'A', text: 'Снизить скорость и увеличить дистанцию до впереди идущего автомобиля' },
            { id: 'B', text: 'Увеличить скорость и уменьшить дистанцию' },
            { id: 'C', text: 'Выехать на обочину' },
        ],
        correctOption: 'A',
    },
    {
        id: 13,
        text: 'Ваши действия при движении прямо?',
        image: 'https://kulager-auto.kz/storage/questions/video/L2LmQNhP0bvHgzS12fpPvwq2uLcaPsYmZOHDhPHE.mp4',
        options: [
            { id: 'A', text: 'Уступите дорогу трамваю' },
            { id: 'B', text: 'Проедете перекресток первым' },
        ],
        correctOption: 'B',
    },
    {
        id: 14,
        text: 'Эксплуатация транспортного средства разрешается, если:',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Не работают в установленном режиме внешние световые приборы' },
            { id: 'B', text: 'Загрязнены внешние световые приборы и световозвращатели' },
            { id: 'C', text: 'Отсутствуют противотуманные фары' },
            { id: 'D', text: 'На световых приборах отсутствуют рассеиватели, либо используются рассеиватели и лампы, не соответствующие типу данного светового прибора' },
        ],
        correctOption: 'C',
    },
    {
        id: 15,
        text: 'Разрешается ли Вам проехать железнодорожный переезд в данной ситуации?',
        image: 'https://kulager-auto.kz/storage/questions/video/9vb35ywy8MHtJP74AervBV8N134e4FkdPcSsVJ2m.mp4',
        options: [
            { id: 'A', text: 'Разрешается, так как дежурный по переезду запрещает движение только встречному автомобилю' },
            { id: 'B', text: 'Запрещается' },
            { id: 'C', text: 'Разрешается, убедившись в отсутствии приближающегося железнодорожного состава' },
        ],
        correctOption: 'B',
    },
    {
        id: 16,
        text: 'В каких направлениях Вам разрешается продолжить движение?',
        image: 'https://kulager-auto.kz/storage/questions/video/439BmQeI2Vt6DUwM9TzA3eE7FWxjm5XpyAPXnbAy.mp4',
        options: [
            { id: 'A', text: 'Только прямо' },
            { id: 'B', text: 'Только направо' },
            { id: 'C', text: 'Налево и в обратном направлении' },
            { id: 'D', text: 'Налево и в обратном направлении' },
            { id: 'E', text: 'Во всех направлениях разрешается' },
        ],
        correctOption: 'A',
    },
    {
        id: 17,
        text: 'В чем опасность длительного торможения автомобиля с выключенным сцеплением (передачей) на крутом затяжном спуске?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'В повышенном износе шин' },
            { id: 'B', text: 'В повышенном износе деталей сцепления (трансмиссии)' },
            { id: 'C', text: 'В перегреве тормозных механизмов' },
        ],
        correctOption: 'C',
    },
    {
        id: 18,
        text: 'Нарушения правил остановки или стоянки транспортных средств в местах, отведенных для остановки или стоянки транспортных средств лиц с инвалидностью, влечет:',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Штраф в размере 10 МРП' },
            { id: 'B', text: 'Штраф в размере 20 МРП' },
            { id: 'C', text: 'Штраф в размере 50 МРП' },
        ],
        correctOption: 'A',
    },
    {
        id: 19,
        text: 'Что означает поднятая вверх рука водителя легкового автомобиля?',
        image: 'https://kulager-auto.kz/storage/questions/video/qHgZR5wd4cq6dUiLMkrD1Djm4AssONm5oWETxMWl.mp4',
        options: [
            { id: 'A', text: 'О его намерении продолжить движение прямо' },
            { id: 'B', text: 'О его намерении повернуть направо' },
            { id: 'C', text: 'О его намерении остановиться, чтобы уступить дорогу' },
            { id: 'D', text: 'О его намерении предупредить Вас об опасности' },
        ],
        correctOption: 'C',
    },
    {
        id: 20,
        text: 'Кому Вы уступите дорогу при повороте направо?',
        image: 'https://kulager-auto.kz/storage/questions/video/ABNscRvParzPL28MkwjgIUrYqhZvNXq9dIbNNSCb.mp4',
        options: [
            { id: 'A', text: 'Только пешеходу I' },
            { id: 'B', text: 'Только пешеходу II' },
            { id: 'C', text: 'Пешеходам I и II' },
        ],
        correctOption: 'C',
    },
    {
        id: 21,
        text: 'При выезде на участок с круговым движением Вы:',
        image: 'https://kulager-auto.kz/storage/questions/video/ALeqJTOdh3f15YtFCFRbfTkBJ51KiqOl2dDHKD0a.mp4',
        options: [
            { id: 'A', text: 'При выезде на перекресток должны уступить дорогу приближающемуся слева легковому автомобилю серого цвета' },
            { id: 'B', text: 'При выезде на перекресток не должны уступать дорогу приближающемуся слева легковому автомобилю серого цвета' },
        ],
        correctOption: 'B',
    },
    {
        id: 22,
        text: 'Разрешается ли Вам осуществить перевозку груза таким образом?',
        image: 'https://kulager-auto.kz/storage/questions/video/1foMllp5bnB9vT72KVn9Fj81mUBfO16YgN5jD2bk.mp4',
        options: [
            { id: 'A', text: 'Разрешается' },
            { id: 'B', text: 'Запрещается' },
        ],
        correctOption: 'B',
    },
    {
        id: 23,
        text: 'Разрешается ли Вам разворот по указанной траектории?',
        image: 'https://kulager-auto.kz/storage/questions/video/f1RzTtdaV0YYFmcsfTmFT8SdYyTZ6D6zRGtYnJBz.mp4',
        options: [
            { id: 'A', text: 'Запрещается' },
            { id: 'B', text: 'Разрешается' },
            { id: 'C', text: 'Запрещается при приближении железнодорожного состава' },
        ],
        correctOption: 'B',
    },
    {
        id: 24,
        text: 'По какой из указанных траекторий Вам разрешено выполнить объезд препятствия?',
        image: 'https://kulager-auto.kz/storage/questions/video/65Wiolc9ymWPWla9RmoFxnCMzQjNA48uCbUVPO3r.mp4',
        options: [
            { id: 'A', text: 'Только по траектории I' },
            { id: 'B', text: 'Только по траектории II' },
            { id: 'C', text: 'По обеим из указанных траекторий' },
        ],
        correctOption: 'A',
    },
    {
        id: 25,
        text: 'Кому Вы уступите дорогу при повороте налево?',
        image: 'https://kulager-auto.kz/storage/questions/video/txwcdqbtL6iYmAvdxLYfHGmMU1R0YTqz7IkVudQU.mp4',
        options: [
            { id: 'A', text: 'Только автобусу' },
            { id: 'B', text: 'Только автомобилю с включенным проблесковым маячком и специальным звуковым сигналом' },
            { id: 'C', text: 'Обоим транспортным средствам' },
            { id: 'D', text: 'Никому' },
        ],
        correctOption: 'B',
    },
    {
        id: 26,
        text: 'В каких направлениях Вам разрешается проехать перекресток, управляя грузовым автомобилем с разрешенной максимальной массой менее 3,5 тонн?',
        image: 'https://kulager-auto.kz/storage/questions/video/nwKHpmdQ0dl7ADqKzQuKdGZfs4nLtkrDyxvOqVB1.mp4',
        options: [
            { id: 'A', text: 'Только направо' },
            { id: 'B', text: 'Направо, налево и в обратном направлении' },
            { id: 'C', text: 'В любых направлениях' },
        ],
        correctOption: 'C',
    },
    {
        id: 27,
        text: 'По каким из указанных траекторий Вам разрешается выполнить разворот?',
        image: 'https://kulager-auto.kz/storage/questions/video/4urpINrJQrDhwyVAYYVZHm9HHBfE4yFlRhKJozKV.mp4',
        options: [
            { id: 'A', text: 'Только по траектории I' },
            { id: 'B', text: 'Только по траектории II' },
            { id: 'C', text: 'По траекториям I и III' },
            { id: 'D', text: 'По всем указанным траекториям разрешается' },
            { id: 'E', text: 'Разворот по всем указанным траекториям запрещается' },
        ],
        correctOption: 'A',
    },
    {
        id: 28,
        text: 'Разрешена ли Вам перевозка груза таким образом?',
        image: 'https://kulager-auto.kz/storage/questions/video/FmMr87uGdvfwNbIMewRXmLyKR58LNSOxtPBcJdlg.mp4',
        options: [
            { id: 'A', text: 'Разрешена' },
            { id: 'B', text: 'Запрещена' },
        ],
        correctOption: 'A',
    },
    {
        id: 29,
        text: 'Как влияет на величину тормозного пути торможение с полной буксировкой колес?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Уменьшает тормозной путь' },
            { id: 'B', text: 'Увеличивает тормозной путь' },
            { id: 'C', text: 'Не влияет на величину тормозного пути' },
        ],
        correctOption: 'B',
    },
    {
        id: 30,
        text: 'Ваши действия при движении прямо?',
        image: 'https://kulager-auto.kz/storage/questions/video/gsKIuEke92YXvx2lhc89ueV05BCkVyNMKjXysXPx.mp4',
        options: [
            { id: 'A', text: 'Уступите дорогу трамваю и легковому автомобилю' },
            { id: 'B', text: 'Уступите дорогу только трамваю' },
            { id: 'C', text: 'Проедете перекресток первым' },
        ],
        correctOption: 'B',
    },
    {
        id: 31,
        text: 'Как Вы должны действовать, если на повороте возник занос задней оси переднеприводного автомобиля?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Уменьшить подачу топлива, рулевым колесом стабилизировать движение' },
            { id: 'B', text: 'Притормозить и повернуть рулевое колесо в сторону заноса' },
            { id: 'C', text: 'Значительно увеличить подачу топлива, положение рулевого колеса не менять' },
            { id: 'D', text: 'Слегка увеличить подачу топлива, корректировать направление движения рулевым колесом' },
        ],
        correctOption: 'D',
    },
    {
        id: 32,
        text: 'Кто из водителей не нарушает правила стоянки в данной ситуации?',
        image: 'https://kulager-auto.kz/storage/questions/video/MXTUaQuiCkOjiWTFuJfhoS11fyLGBhfosDjoQyd0.mp4',
        options: [
            { id: 'A', text: 'Только водитель грузового автомобиля' },
            { id: 'B', text: 'Водитель мотоцикла и легкового автомобиля' },
            { id: 'C', text: 'Все водители нарушают' },
            { id: 'D', text: 'Никто из водители не нарушает' },
        ],
        correctOption: 'D',
    },
    {
        id: 33,
        text: 'Что нужно сделать для свободного прохождения воздуха в легкие при проведении реанимации?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Расстегнуть одежду, подложить валик под голову' },
            { id: 'B', text: 'Подложить валик под лопатки' },
            { id: 'C', text: 'Запрокинуть голову, приподнять подбородок и открыть рот' },
        ],
        correctOption: 'C',
    },
    {
        id: 34,
        text: 'Как Вы поступите при установке данного дорожного знака перед перекрестком?',
        image: 'https://kulager-auto.kz/storage/questions/video/BK4XfLv4Ne7WamNN9yBgmcNWKMjmzWkNebsxZghC.mp4',
        options: [
            { id: 'A', text: 'Остановитесь перед знаком 2.5 "Движение без остановки запрещено"' },
            { id: 'B', text: 'Остановитесь перед стоп-линией' },
            { id: 'C', text: 'Остановитесь перед краем пересекаемой проезжей части' },
            { id: 'D', text: 'Продолжите движение без остановки, убедившись в отсутствии приближающихся транспортных средств' },
        ],
        correctOption: 'B',
    },
    {
        id: 35,
        text: 'Как влияет Ваше утомление на внимание и реакцию?',
        image: 'https://kulager-auto.kz/build/assets/no-img-e2061fbc.png',
        options: [
            { id: 'A', text: 'Ваше внимание и реакция повышается' },
            { id: 'B', text: 'Ваше внимание и реакция снижается' },
            { id: 'C', text: 'На Ваше внимание и реакцию, утомление никак не влияет' },
        ],
        correctOption: 'B',
    },
    {
        id: 36,
        text: 'При приближении сзади транспортного средства с более высокой скоростью и подающим предупредительный сигнал, водитель автомобиля желтого цвета:',
        image: 'https://kulager-auto.kz/storage/questions/video/QitEemkjnfhQJEDsSuryDNsgjDJ0qvpl3SiDqDwT.mp4',
        options: [
            { id: 'A', text: 'Продолжит свое движение не меняя полосы движения' },
            { id: 'B', text: 'Освободит занимаемую им полосу движения с перестроением вправо' },
            { id: 'C', text: 'Продолжит свое движение не меняя полосы движения, если его скорость равна разрешенной' },
        ],
        correctOption: 'C',
    },
    {
        id: 37,
        text: 'Разрешено ли Вам подъехать к дому, в котором проживаете, расположенному за знаком?',
        image: 'https://kulager-auto.kz/storage/questions/video/xbTPemn6jnVxS2FcwyI0zLxnogNy4KwGhuzVda3Q.mp4',
        options: [
            { id: 'A', text: 'Разрешено' },
            { id: 'B', text: 'Разрешено, но только с противоположного направления' },
            { id: 'C', text: 'Разрешено, но только включив аварийную световую сигнализацию' },
            { id: 'D', text: 'Запрещено' },
        ],
        correctOption: 'A',
    },
    {
        id: 38,
        text: 'Какие из указанных дорожных знаков информирует Вас о начале дороги с реверсивным движением?',
        image: 'https://kulager-auto.kz/storage/questions/video/B4ZN1JZcnnZyC1SIkYvVInX4raTNqiXowwjVOgZT.mp4',
        options: [
            { id: 'A', text: 'Знак I' },
            { id: 'B', text: 'Знак II' },
            { id: 'C', text: 'Знак III' },
            { id: 'D', text: 'Знак IV' },
        ],
        correctOption: 'C',
    },
    {
        id: 39,
        text: 'Какой из указанных дорожных знаков запрещает проезд без остановки у контрольного пункта?',
        image: 'https://kulager-auto.kz/storage/questions/video/M9b39pmLNP1RDerytJZafrw0Po3hmZhHp5TITkxw.mp4',
        options: [
            { id: 'A', text: 'Знак I' },
            { id: 'B', text: 'Знак II' },
            { id: 'C', text: 'Знак III' },
            { id: 'D', text: 'Знак IV' },
            { id: 'E', text: 'Знак V' },
        ],
        correctOption: 'C',
    },
    {
        id: 40,
        text: 'Разрешается ли Вам выполнить разворот на мосту?',
        image: 'https://kulager-auto.kz/storage/questions/video/O42NTyp9HmYIoRjfKhfcHiQ5fZNDDm7mcNBjyGZd.mp4',
        options: [
            { id: 'A', text: 'Разрешается при отсутствии встречных транспортных средств' },
            { id: 'B', text: 'Разрешается только при видимости дороги более 100 метров' },
            { id: 'C', text: 'Запрещается' },
        ],
        correctOption: 'C',
    },
]